### PR TITLE
added few unit tests

### PR DESCRIPTION
**Pull request by jeromechrist**
#20 

added few unit tests for functions in MockDraftPick

### CODE REVIEW

**Comment by robsmithw** [comment]
Just a small comment on this I would modify the hard coded state name and city/state abrev names into constants.
This does two things:
1. Make it easier to modify the test in the future
2. You can reuse the same state and/or city state abrev for future test that are developed.

It was a super small change, but I did a PR into your forked branch if you want to merge and update, totally up to you though.
PR: https://github.com/jeromechrist/prospect-scraper-dt2021/pull/1

**Review by zo0o0ot — APPROVED** [review]
This looks good.  Thanks!

**Review by zo0o0ot — CHANGES_REQUESTED** [review]
I merged in a refactoring which appears to cause a conflict here.  Sorry about that.  Would you be willing to update your tests?

I think the big change will be that the method names are all capitalized now.

**Comment by jeromechrist** [comment]
hello, yes sure ! I've updated the branch

**Review by zo0o0ot — APPROVED** [review]
Looks good!

**Pull request merged**
