### PR TITLE
#20 Add unit tests to cover a random collection of functionality.

### PR DESCRIPTION
**Pull request by ScottBurfieldMills**
- Converting height from "ft" to "inches"
- Logic around draft dates
- School name mapping

### CODE REVIEW

**Comment by ScottBurfieldMills** [comment]
I'm not too familiar with GitHub actions. Can someone please point me in the right direction to fix this issue?

`Error: Resource not accessible by integration`

**Comment by zo0o0ot** [comment]
This GitHub action failure isn't your fault.  For more info, see this:
https://github.com/actions/first-interaction/issues/10

**Comment by zo0o0ot** [comment]
The greetings.yml action is supposed to greet new folks, but apparently it freaks out if you don't have access to the organization.  I think they're working on fixing the action.

**Review by zo0o0ot — APPROVED** [review]
Looks good!

**Pull request merged**
